### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by Herython** [IShiraiKurokoI/DLUTToolBoxV3#1]
![Snipaste_2023-03-29_18-15-22](https://user-images.githubusercontent.com/69076602/228503160-4e23f8e5-97e9-4075-bb2c-deb21085d907.png)

**Comment by IShiraiKurokoI** [comment]
> ![Snipaste_2023-03-29_18-15-22](https://user-images.githubusercontent.com/69076602/228503160-4e23f8e5-97e9-4075-bb2c-deb21085d907.png)

如果可以的话能否提供一下操作系统版本，win10 1909之前的版本可能无法安装

**Comment by Herython** [comment]
> 

win10专业版22H2

**Comment by IShiraiKurokoI** [comment]
> > 
> 
> win10专业版22H2

可以尝试设置中检查下开发者选项中的开发人员模式是否打开
另外这个提示理论上应该会提出需要什么程序包 比如 
`应用安装程序无法安装应用包相关项。请向开发人员索要 Microsoft.VCLibs.120.00 应用包`
release中三个版本对应的是三种不同处理器架构的发布版本（仅仅测试过了X64）
可以参考下这两篇文章
https://learn.microsoft.com/zh-cn/windows/msix/app-installer/troubleshoot-appinstaller-issues
https://www.mulingyuer.com/archives/566/#:~:text=appx%E5%AE%89%E8%A3%85%EF%BC%9A,%E8%AF%BB%E6%9D%A1%E5%AE%8C%E6%AF%95%EF%BC%8C%E5%AE%89%E8%A3%85%E6%88%90%E5%8A%9F%EF%BC%81&text=%E4%BB%A5%E4%B8%8A%E5%AE%8C%E6%AF%95%EF%BC%81

**Comment by Herython** [comment]
> > > 
> > 
> > 
> > win10专业版22H2
> 
> 可以尝试设置中检查下开发者选项中的开发人员模式是否打开 另外这个提示理论上应该会提出需要什么程序包 比如 `应用安装程序无法安装应用包相关项。请向开发人员索要 Microsoft.VCLibs.120.00 应用包` release中三个版本对应的是三种不同处理器架构的发布版本（仅仅测试过了X64） 可以参考下这两篇文章 https://learn.microsoft.com/zh-cn/windows/msix/app-installer/troubleshoot-appinstaller-issues https://www.mulingyuer.com/archives/566/#:~:text=appx%E5%AE%89%E8%A3%85%EF%BC%9A,%E8%AF%BB%E6%9D%A1%E5%AE%8C%E6%AF%95%EF%BC%8C%E5%AE%89%E8%A3%85%E6%88%90%E5%8A%9F%EF%BC%81&text=%E4%BB%A5%E4%B8%8A%E5%AE%8C%E6%AF%95%EF%BC%81

![Snipaste_2023-03-29_18-37-20](https://user-images.githubusercontent.com/69076602/228508308-802097a2-75a6-41a3-a089-e7b876b4ad71.png)

**Comment by Herython** [comment]
> > > 
> > 
> > 
> > win10专业版22H2
> 
> 可以尝试设置中检查下开发者选项中的开发人员模式是否打开 另外这个提示理论上应该会提出需要什么程序包 比如 `应用安装程序无法安装应用包相关项。请向开发人员索要 Microsoft.VCLibs.120.00 应用包` release中三个版本对应的是三种不同处理器架构的发布版本（仅仅测试过了X64） 可以参考下这两篇文章 https://learn.microsoft.com/zh-cn/windows/msix/app-installer/troubleshoot-appinstaller-issues https://www.mulingyuer.com/archives/566/#:~:text=appx%E5%AE%89%E8%A3%85%EF%BC%9A,%E8%AF%BB%E6%9D%A1%E5%AE%8C%E6%AF%95%EF%BC%8C%E5%AE%89%E8%A3%85%E6%88%90%E5%8A%9F%EF%BC%81&text=%E4%BB%A5%E4%B8%8A%E5%AE%8C%E6%AF%95%EF%BC%81

始终只显示`应用安装程序无法安装应用包相关项。请向开发人员索要  应用包`

**Comment by IShiraiKurokoI** [comment]
> > > > 
> > > 
> > > 
> > > win10专业版22H2
> > 
> > 
> > 可以尝试设置中检查下开发者选项中的开发人员模式是否打开 另外这个提示理论上应该会提出需要什么程序包 比如 `应用安装程序无法安装应用包相关项。请向开发人员索要 Microsoft.VCLibs.120.00 应用包` release中三个版本对应的是三种不同处理器架构的发布版本（仅仅测试过了X64） 可以参考下这两篇文章 https://learn.microsoft.com/zh-cn/windows/msix/app-installer/troubleshoot-appinstaller-issues https://www.mulingyuer.com/archives/566/#:~:text=appx%E5%AE%89%E8%A3%85%EF%BC%9A,%E8%AF%BB%E6%9D%A1%E5%AE%8C%E6%AF%95%EF%BC%8C%E5%AE%89%E8%A3%85%E6%88%90%E5%8A%9F%EF%BC%81&text=%E4%BB%A5%E4%B8%8A%E5%AE%8C%E6%AF%95%EF%BC%81
> 
> ![Snipaste_2023-03-29_18-37-20](https://user-images.githubusercontent.com/69076602/228508308-802097a2-75a6-41a3-a089-e7b876b4ad71.png)

报错里写出来了问题，你的appruntime版本过低，你电脑上的版本是2000.777，最低需要2000.802
可以通过以下链接来下载和检查运行时版本
https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads
https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/check-windows-app-sdk-versions

**Comment by Herython** [comment]
问题解决了，多谢
