### ISSUE TITLE
安装后无法打开

### ISSUE THREAD

**Issue by Herython** [IShiraiKurokoI/DLUTToolBoxV3#2]
https://user-images.githubusercontent.com/69076602/236535555-b043aa42-8225-46ae-8b57-6a85f848c805.mp4

**Comment by IShiraiKurokoI** [comment]
如果可以的话，提供一下系统版本和处理器架构信息，这样的话我可以尝试复现一下，谢谢

**Comment by Herython** [comment]
> 如果可以的话，提供一下系统版本和处理器架构信息，这样的话我可以尝试复现一下，谢谢

处理器: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz   2.30 GHz
系统版本: Win10专业版22H2

**Comment by IShiraiKurokoI** [comment]
我更新了1.2.4.0版本，优化了对于Windows10 系统的兼容性检测，并且增加了全局报错捕获。另外，由于微软更新了appsdk到1.3版本，可以尝试下更新Windowsappsdk。如果仍然存在无法打开的问题，可以查看下 %userprofile%\Documents\DLUTToolBoxV3\Log 目录下的日志，或许能提供有用的信息。

**Comment by IShiraiKurokoI** [comment]
> > 如果可以的话，提供一下系统版本和处理器架构信息，这样的话我可以尝试复现一下，谢谢
> 
> 处理器: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz 2.30 GHz 系统版本: Win10专业版22H2

找到问题了，win10的特定版本会触发第三方库中的版本检测，导致调用了一句传递错误主题颜色类型的代码，我已经将这个问题报告给第三方库的作者，然后暂时发布一个beta版本，在检测到特定win10版本后屏蔽主题设置来防止报错

**Comment by IShiraiKurokoI** [comment]
问题解决了 
请使用新版本1.2.6.0 https://github.com/IShiraiKurokoI/DLUTToolBoxV3/releases/tag/1.2.6.0
感谢您的支持与反馈！

**Comment by Herython** [comment]
[](url)
![Snipaste_2023-05-10_09-45-11](https://github.com/IShiraiKurokoI/DLUTToolBoxV3/assets/69076602/3de5bf30-1526-4cc3-ace6-e9fb9f10aa04)

**Comment by IShiraiKurokoI** [comment]
> ![Snipaste_2023-05-10_09-45-11](https://user-images.githubusercontent.com/69076602/237257183-3de5bf30-1526-4cc3-ace6-e9fb9f10aa04.jpg)

这个问题第三方库的作者在我昨天提出issue后已经修复了，我也已经一同更新了程序，可以卸载原先的应用然后下载（可能您下载了错误的版本）新版本地址：https://github.com/IShiraiKurokoI/DLUTToolBoxV3/releases/tag/1.2.8.0
已经在虚拟机和多个实体机环境下测试过了，并未发现问题。
