### ISSUE TITLE
mac版本

### ISSUE THREAD

**Issue by zrli2000** [IShiraiKurokoI/DLUTToolBoxV3#3]
尊敬的开发者哥哥，什么时候可以开发一个mac版本的呀，好期待~

**Comment by IShiraiKurokoI** [comment]
等我忙完这段时间的吧，有时间会考虑的

**Comment by Fruckin** [comment]
开发者哥哥，有时间开发mac版本的了嘛

**Comment by IShiraiKurokoI** [comment]
> 开发者哥哥，有时间开发mac版本的了嘛

已经在开发了

**Comment by Fruckin** [comment]
开发者哥哥，啥时候能开发好Mac版本的呀~

**Comment by IShiraiKurokoI** [comment]
> 开发者哥哥，啥时候能开发好Mac版本的呀~

基本上除了实时电费查询已经写好了，是新使用electron重构的，详情可以查看https://github.com/IShiraiKurokoI/DLUTToolBox-electron  ，如果新的electron版本有问题可以在那个新的仓库提出issue。
