### ISSUE TITLE
开机自动登录校园网坏了

### ISSUE THREAD

**Issue by Dyinglight5** [IShiraiKurokoI/DLUTToolBoxV3#4]
开机使用工具箱连不上
[Log-DLUTToolBoxV3-2024-09-15.log](https://github.com/user-attachments/files/17004284/Log-DLUTToolBoxV3-2024-09-15.log)
查询电费功能也失效了

**Comment by IShiraiKurokoI** [comment]
看日志是DNS解析不到sso.dlut.edu.cn,你试试清除dns缓存和网络修复，不过我看最后还是获取到了ticket拼接了登陆链接，可能是校园网登陆方式变了？你抓包梳理一下登陆跳转流程，我看一下。或者你直接改好提pr也行。另外开机自动登录的日志应该是在Documents\DLUTToolBoxV3\EDALoginModuleLog里。

**Comment by Dyinglight5** [comment]
我把开机自动连接关了好像就能直接连上了，可能是校园网这两天抽风的原因哈哈哈
[Log-DLUTToolBoxV3-2024-09-15.log](https://github.com/user-attachments/files/17004411/Log-DLUTToolBoxV3-2024-09-15.log)
